name: CMake build test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - name: checkout 
      uses: actions/checkout@v1
    - name: install qt
      uses: jurplel/install-qt-action@v1
    - name: cmake
      run: cmake .
    - name: make
      run: make
