name: CMake build test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - name: install qt
      uses: actions/install-qt-action@v0.1.1
      with:
        packages: 'qt.qt5.5124.gcc_64'
    - name: Test qmake
      run: QT_QMAKE_EXECUTABLE="/Qt/5.12.4/gcc_64/bin/qmake" cmake .
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
